# Generated by Django 4.2.4 on 2023-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends_only', 'Friends Only'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
